apiVersion: v1
kind: Pod
metadata:
  name: hello-sillot
  labels:
    app: hello-sillot
spec:
  containers:
  - name: hello-sillot
    image: miguelperezcolom/hello-sillot:latest
    ports:
      - containerPort: 8080
    env:
      - name: EMAIL_USERNAME
        valueFrom:
          secretKeyRef:
            name: hello-sillot-secret
            key: EMAIL_USERNAME
      - name: EMAIL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: hello-sillot-secret
            key: EMAIL_PASSWORD

---
kind: Service
apiVersion: v1
metadata:
  name: hello-sillot
spec:
  type: NodePort
  selector:
    app: hello-sillot
  ports:
    - nodePort: 30821
      port: 821
      targetPort: 8080
